### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by Mycobee** [josh-everett01/travel_tracker#5]
## Description:
Github has a nifty feature called a pull request template.  Whenever you open a pull request, it will auto-fill it with this template so you can describe the changes you implemented. 

Add a pull request template to your repository with the following text

```
## Changes proposed by this PR
closes #

## What did you struggle on to complete?

## Checklist:
- [ ] code has been linted with JSHint
- [ ] I have reviewed my code
- [ ] all issue criteria is completed 
- [ ] I have fully styled all changes

## Helpful Resources:
[link_1](https://example_resource.com)
[link_2](https://example_resource_2.com)
```

### Checks:

- [x] I have added a pull request markdown template to my repository
- [x] I have properly written a concise commit message

**Comment by josh-everett01** [comment]
Template is showing in my root directory now so it should be working correctly next time I make a pull request?
