### ISSUE TITLE
Integrate HoundCI

### ISSUE THREAD

**Issue by Mycobee** [josh-everett01/travel_tracker#6]
## Description

HoundCI is a tool that will ensure our code runs through a linter on github before it is merged in to master.  This is very helpful as it will ensure all code is up to the appropriate standards and quality.  

Integrate HoundCI for the travel tracker project, using your github account

### Checks
- [x] successfully implemented houndCI to lint all new pull requests

**Comment by josh-everett01** [comment]
Ok I have added this Repo and activated it. Should be active next time we open a PR?

**Comment by josh-everett01** [comment]
@Mycobee I think this is complete. It should be verified when we merge our next PR.
