### ISSUE TITLE
Deploy project to Github Pages

### ISSUE THREAD

**Issue by Mycobee** [josh-everett01/travel_tracker#9]
## Description:
The travel tracker application should be deployed on github pages, where a live link can be followed.  Set this up to track the master branch, and add a comment in this issue upon completion

### Checks:
- [x] travel_tracker repository is deployed on github pages, tracking the master branch
- [x] before dragging this issue to complete, a comment has been added that links to the github pages url

**Comment by josh-everett01** [comment]
https://josh-everett01.github.io/travel_tracker/
 👍
